### ISSUE TITLE
Change position of controls?

### ISSUE THREAD

**Issue by LFeh** [afonsopacifer/react-pomodoro#12]
Do you think a good idea change the position of controls for below the types of timer?

We can increase the size of icons too, then it can facilitates the pause and play of pomodoros.

![untitled image](https://cloud.githubusercontent.com/assets/3603793/14955498/b3135046-1050-11e6-9c2d-18e413fe2b36.png)

**Comment by afonsopacifer** [comment]
I made an example on photoshop!

![mod](https://cloud.githubusercontent.com/assets/6748866/15021326/87700422-11fc-11e6-97dc-795cecc7798b.jpg)

Really it got better :)

**Comment by LFeh** [comment]
Perfect! Was exatly this that I had imagined! haha

If you want, I can make this changes.

**Comment by afonsopacifer** [comment]
Done,
Is available in  [v 0.3.0](https://github.com/afonsopacifer/react-pomodoro/releases/tag/0.3.0) :)
