### ISSUE TITLE
Start count when click in timer type?

### ISSUE THREAD

**Issue by LFeh** [afonsopacifer/react-pomodoro#13]
I was use the [Pomodoro-Timer](http://tomato-timer.com/) and it has a good feature: When click in the timer type, it starts the count.  I think that this helps the use.

Do you like this funcionality?

**Comment by afonsopacifer** [comment]
I think is cool! 
This change really accelerate productivity :)

You want to send a PR ? or I can do here =D

**Comment by LFeh** [comment]
@afonsopacifer I never developed using React, but I can try ;)

**Comment by LFeh** [comment]
Do you view my other issue? #12

**Comment by shakegioh** [comment]
I did it, hope you guys don't mind

**Comment by cauealves** [comment]
I think this issue can be closed. 

cc @afonsopacifer
