### ISSUE TITLE
Use ES6 classes and stateless functions

### ISSUE THREAD

**Issue by mkautzmann** [afonsopacifer/react-pomodoro#14]
Hi.

Great project!

I noticed that the project is using React 15.0.1 and since ES6 is already present in the codebase I figured we might want to switch to an ES6 class in the `Pomodoro` component and a stateless function in the `Footer` component.

What do you think?

Those are quick changes and I am happy to send a PR if you agree with them.

Thank you 😎

**Comment by afonsopacifer** [comment]
Hello @mkautzmann,
I think is cooool 👍 

(PS: Mete bronca aew mano ;D)

**Comment by mkautzmann** [comment]
I created a branch called `react-refactor` locally. Should I PR to `master` or can you create a new branch for this change?

**Comment by afonsopacifer** [comment]
I created a branch `development`.
You can send your PR for this branch :)

**Comment by afonsopacifer** [comment]
Great!
Thanks @mkautzmann :)
