### ISSUE TITLE
Ctrl + Left and Right doesn't works on Mac OS X

### ISSUE THREAD

**Issue by cauealves** [afonsopacifer/react-pomodoro#36]
Stack:
-  `Google Chrome 51.0.2704.79 (64-bit)`
- `OS X El Capitan 10.11.5`

**Comment by afonsopacifer** [comment]
What do you think for change for Atl + arrows?

**Comment by cauealves** [comment]
It seems to be a good option. Because, the `ALT` is on the side of the `ARROWS` and facilitates use. 

But I believe we have to understand the `CTRL` problem, because it can happen with the `ALT` too.

**Comment by cauealves** [comment]
`ALT` only for MAC keyboard's. :)

**Comment by shakegioh** [comment]
Do you think it's a good choice to use ALT only for MACs?
I guess it would be better to choose whether to keep _Ctrl on Windows and CMD on MACs_ or _change both to ALT_.

**Comment by cauealves** [comment]
It's cool too.

But @shakegioh, do you know the reason of doesn't works now?

**Comment by shakegioh** [comment]
The `command` key wasn't bind to the shortcuts
