### ISSUE TITLE
Ask for notification

### ISSUE THREAD

**Issue by willianjusten** [afonsopacifer/react-pomodoro#6]
The notification API require user's permission to show on desktop. We should ask this permission when click to enable notification.

**Comment by afonsopacifer** [comment]
I added the ask on componentdidmount "event"

```js
  componentDidMount() {
    this.setTime(1500);
    Notification.requestPermission();
  },
```
![screen shot 2016-05-01 at 8 22 47 pm](https://cloud.githubusercontent.com/assets/6748866/14944955/700ad4d4-0fda-11e6-901b-1586b0db8452.png)

**Comment by mkautzmann** [comment]
It's working here now, is this still a problem?

**Comment by afonsopacifer** [comment]
No, it's ok
